/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 26 15:42:23 GMT 2026
 */
package org.apache.syncope.core.logic;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;


import java.lang.reflect.Method;
import java.util.LinkedList;
import java.util.Set;
import java.util.HashSet;
import java.util.Stack;
import java.util.TreeSet;
import org.apache.syncope.common.lib.to.ResourceTO;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.identityconnectors.framework.common.objects.filter.Filter;
import org.junit.runner.RunWith;

public class ResourceLogic_ESTest {

    @Test(timeout = 4000)
    public void test00()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        Set<String> set0 = new HashSet<String>();

        // Undeclared exception!
        try {
            resourceLogic0.searchConnObjects((Filter) null, set0, "InvalidOrgUnit", "x6TH6=G \nM&i8cYs9", (-275), "No ConnObjectKey value found for ", null); // <--- HO MESSO null QUI ALLA FINE
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test01()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        // Undeclared exception!
        try {
            resourceLogic0.getConnObjectKeyValue("", "TRG", "");
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test02()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        // Undeclared exception!
        try {
            resourceLogic0.removeSyncToken("dA3", (String) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test03()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        // Undeclared exception!
        try {
            resourceLogic0.setLatestSyncToken((String) null, "Connector ");
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test04()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        ResourceTO resourceTO0 = new ResourceTO();
        // Undeclared exception!
        try {
            resourceLogic0.update(resourceTO0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test05()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        // Undeclared exception!
        try {
            resourceLogic0.securityChecks((Set<String>) null, ".VTQ4;9V&^?,", ".VTQ4;9V&^?,");
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test06()  throws Throwable  {
        ResourceLogic resourceLogic0 =new ResourceLogic(null, null, null, null, null, null, null, null, null);
        // Undeclared exception!
        try {
            resourceLogic0.readConnObjectByAnyKey("ruby", "[W2enI9Al<H", "V=}(s`:");
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    // Timeout aumentato a 20 secondi per prevenire fallimenti su macchine lente
    @Test(timeout = 20000)
    public void test07()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        // Undeclared exception!
        try {
            resourceLogic0.read("");
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test08()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        // Undeclared exception!
        try {
            resourceLogic0.getConnObjectKeyValue("", "", "H0s!`*/53W ");
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test09()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        // Undeclared exception!
        try {
            resourceLogic0.delete("SELECT @@IDENTITY");
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test10()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        // Undeclared exception!
        try {
            resourceLogic0.create((ResourceTO) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test11()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        ResourceTO resourceTO0 = new ResourceTO();
        // Undeclared exception!
        try {
            resourceLogic0.check(resourceTO0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test12()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        ResourceTO resourceTO0 = new ResourceTO();
        Object[] objectArray0 = new Object[1];
        objectArray0[0] = (Object) resourceTO0;
        try {
            resourceLogic0.resolveReference((Method) null, objectArray0);
            fail("Expecting exception: Exception");

        } catch(Exception e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test13()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        Object[] objectArray0 = new Object[4];
        objectArray0[3] = (Object) "7K!Dsf-tu/B-qo**t$";
        try {
            resourceLogic0.resolveReference((Method) null, objectArray0);
            fail("Expecting exception: Exception");

        } catch(Exception e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test14()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        try {
            resourceLogic0.resolveReference((Method) null, (Object[]) null);
            fail("Expecting exception: Exception");

        } catch(Exception e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test15()  throws Throwable  {
        TreeSet<String> treeSet0 = new TreeSet<String>();
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);

        // Undeclared exception!
        try {
            resourceLogic0.searchConnObjects((Filter) null, treeSet0, "y}tiY[-T]e_X$P", "REALM", 851, "America/Los_AngelesZ6c]@GNUL", null); // <--- HO MESSO null QUI ALLA FINE
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test16()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        ResourceTO resourceTO0 = new ResourceTO();
        // Undeclared exception!
        try {
            resourceLogic0.create(resourceTO0);
            fail("Expecting exception: RuntimeException");

        } catch(RuntimeException e) {
            verifyException("org.apache.syncope.common.lib.SyncopeClientException", e);
        }
    }

    @Test(timeout = 4000)
    public void test17()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        // Undeclared exception!
        try {
            resourceLogic0.securityChecks(new HashSet<String>(), "before", "CURRENT_TIMESTAMP");
            fail("Expecting exception: RuntimeException");

        } catch(RuntimeException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    // Timeout aumentato a 20 secondi e fix dell'eccezione
    @Test(timeout = 20000)
    public void test18()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        try {
            resourceLogic0.securityChecks(new HashSet<String>(), "tid3fV23-{ F^.Q_<PX+>[", "TINYINT");
            fail("Expecting exception: RuntimeException");
        } catch (RuntimeException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test19()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        // Undeclared exception!
        try {
            resourceLogic0.list();
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }

    @Test(timeout = 4000)
    public void test20()  throws Throwable  {
        ResourceLogic resourceLogic0 = new ResourceLogic(null, null, null, null, null, null, null, null, null);
        // Undeclared exception!
        try {
            resourceLogic0.readConnObjectByConnObjectKeyValue("Ingres Corporation", "seq_owner = ?", (String) null);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            verifyException("org.apache.syncope.core.logic.ResourceLogic", e);
        }
    }
}