/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 26 16:34:57 GMT 2026
 */

package org.apache.syncope.core.provisioning.java.pushpull;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.syncope.core.provisioning.api.pushpull.SyncopePullExecutor;
import org.apache.syncope.core.provisioning.java.pushpull.DefaultRealmPullResultHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.identityconnectors.framework.common.objects.SyncDelta;
import org.junit.runner.RunWith;

public class DefaultRealmPullResultHandler_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultRealmPullResultHandler defaultRealmPullResultHandler0 = new DefaultRealmPullResultHandler();
      // Undeclared exception!
      try { 
        defaultRealmPullResultHandler0.handle((SyncDelta) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.provisioning.java.pushpull.DefaultRealmPullResultHandler", e);
      }
  }

}
