name: Apache Syncope CI - Build and Validation

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'oracle'
          cache: maven

      - name: Compilazione veloce
        run: >
          mvn clean test-compile -B -T 1C
          -Denforcer.skip=true
          -Dcheckstyle.skip=true
          -Drat.skip=true
          -Djava.net.preferIPv4Stack=true

      - name: Esecuzione Test
        run: >
          mvn test -B -T 1C
          -Denforcer.skip=true
          -Dcheckstyle.skip=true
          -Drat.skip=true
          -DfailIfNoTests=false
          -Djava.net.preferIPv4Stack=true
          -Dtest=ResourceLogicCFTest,ResourceLogicBBTest,ResourceLogicLLMFew2Test,ResourceLogicLLMFewTest,ResourceLogicLLMToTTest,ResourceLogicLLMToT2Test,ResourceLogicLLMZeroTest,ResourceLogicPITTest,ResourceLogicRandoopRunTest,ResourceLogicRandoopTest,DefaultRealmPullResultHandlerBBTest,DefaultRealmPullResultHandlerCFTest,DefaultRealmPullResultHandlerLLMFew1Test,DefaultRealmPullResultHandlerLLMFew2Test,DefaultRealmPullResultHandlerLLMToT1Test,DefaultRealmPullResultHandlerLLMToT2Test,DefaultRealmPullResultHandlerLLMZeroTest,DefaultRealmPullResultHandlerPITTest,DefaultRealmPullResultHandlerRandoopRunTest,DefaultRealmPullResultHandlerRandoopTest 

      - name: Esecuzione Integration Tests
        run: >
          mvn verify -B
          -Denforcer.skip=true
          -Dcheckstyle.skip=true
          -Drat.skip=true
          -DfailIfNoTests=false
          -Djava.net.preferIPv4Stack=true
          -Dit.test=ResourceLogicITTest,DefaultRealmPullResultHandlerITTest